Add schema, data and queries
D4nielJ/vet-clinic-sql pull request #1
Opened 2021-09-20 21:03 UTC by D4nielJ

## Hello Mr Reviewer

This repo contains:

- Schema for table 'animals'
- Queries to add data to 'animals' table
- Queries to select data from 'animals'

2021-09-20 21:25 UTC, arslanbisharat requested changes
# Changes Requested, 

Hi there, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have limited number of code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-09-20 21:25 UTC, arslanbisharat commented on schema.sql
> +    weight_kg DECIMAL
- [ ] columns should have `VARCHAR` instead of DECIMAL.  Kindly add VARCHAR for all your columns as it determines the length of characters this is best practice 👍. 
- [ ] [OPTIONAL] you can make the id column not null and autoincremented

    `id int NOT NULL IDENTITY(1,1)`

- [ ] [OPTIONAL] you can mark the id column as primary key

      `PRIMARY KEY (id)`

2021-09-20 21:25 UTC, arslanbisharat commented on queries.sql
> +SELECT * FROM animals WHERE name ~'[A-Za-z]+mon';
- [ ] [OPTIONAL] This is a great approach to select animal nams ending with mon. You can try this method too. 
`SELECT * FROM animals WHERE name LIKE '%mon'; `

2021-09-20 22:31 UTC, D4nielJ commented on schema.sql
> +    weight_kg DECIMAL
Hello, thank you for your feedback. Would you be so kind to elaborate on some of the changes requested?

1. Columns might have different data types as stated in the documentation of PostgreSQL, including dates, integers, boolean.

https://www.postgresql.org/docs/13/datatype.html

`id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,`

2. When using GENERATED ALWAYS AS IDENTITY id column becomes NOT NULL, it also uses the SEQUENCE object to define the increment which is 1 by default. You can refer to the following articles:

- https://www.postgresqltutorial.com/postgresql-identity-column/
- https://www.postgresql.org/docs/9.5/sql-createsequence.html

3. ID column is already marked as PRIMARY KEY:

2021-09-20 22:33 UTC, D4nielJ commented on queries.sql
> +SELECT * FROM animals WHERE name ~'[A-Za-z]+mon';
Here are some examples comparing fetching times between LIKE and regex where most of them are faster using regular expressions.

https://codeforlearning.com/how-to-use-regular-expressions-in-postgresql-with-examples/

2021-09-20 22:45 UTC, arslanbisharat requested changes
# Invalid submission 

Hi,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You submitted the project for re-review without making any changes. Please work on the changes first and request another review. Each review is very important to you as you have a limited number of reviews. 
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2021-09-20 23:05 UTC, D4nielJ commented on schema.sql
> +    weight_kg DECIMAL
This is from the Microverse requirements, where columns should have valid data types.

```
`- Create a table named `animals` with the following columns:
  - `id`: integer
  - `name`: string
  - `date_of_birth`: date
  - `escape_attempts`: integer
  - `neutered`: boolean
  - `weight_kg`: decimal`
```

2021-09-21 09:22 UTC, Temmarie commented
Hello  @D4nielJ    :wave:

_This is an additional review as a result of the second opinion request._

You complained about the reviewer's request being vague and not further explaining the review.
Firstly, you need to understand that the reviewers all follow a set of guidelines for the projects and the reviewer was confused with that particular instruction. 
As mentioned by the previous reviewer, regarding the length of characters in the columns, it is advisable for you to use `VARCHAR` as it has an indeterminate length string data type. It can hold numbers, letters and special characters. You can consider using it for the length, but it is also okay for you to use other data types. 

 As this was the only reason why your project was not approved, kindly request for a review and it will be approved immediately by the next code reviewer.
Keep rocking :rocket:!

2021-09-21 09:50 UTC, nidalaa commented
Hello  @D4nielJ  👋,

_This is an additional review as a result of the second opinion request._

Thank you for requesting a second opinion for this issue :)

The main reason for this problem is that we had a mistake with the guidelines for code reviewers.  We discussed it with the group of code reviewers and fixed it but a majority of the reviews that were performed before that discussion were done with the "safe mode"  - by using the guidelines as a pattern.

We really apologize for the inconvenience that it caused.  Good job with defending your point here in a professional way! ❤️ 




-----------

As these were the only reason that your project was not approved it will be approved as soon as possible.
Please ask for another review in your Dashboard and the next Code Reviewer will mark it as approve right away :)

Keep rocking 🚀!

2021-09-21 13:04 UTC, arslanbisharat approved these changes
# Approved 👏 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project which you can see from your dashbaord. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2021-09-21 15:04 UTC, merged